### PR TITLE
add bart

### PR DESCRIPTION
**Pull request by tscholak**
we've got to bump hugging face transformers to a newer version than in nixpkgs to support byt5.
https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/development/python-modules/transformers/default.nix is at 4.4.2 which is several months old.

### CODE REVIEW

**Comment by junjihashimoto** [comment]
It looks like there is no bump code. Should we use transformers-4.8.2?
https://pypi.org/project/transformers

**Comment by tscholak** [comment]
@junjihashimoto I switched to `poetry2nix`, works well.

**Comment by junjihashimoto** [comment]
Awesome!

**Comment by tscholak** [comment]
should I merge this?

**Comment by junjihashimoto** [comment]
Thx! I will try poetry for torchvision.

**Pull request merged**
